spring.application.name: betterreads-data-loader

datadump.location:
  author: /home/avdhoot/Code/test-authors.txt
  works: /home/avdhoot/Code/test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: recreate
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

  main:
    allow-circular-references: true
 

datastax.astra:
    secure-connect-bundle: secure-connect.zip


astra.db:
    id: <db-id>
    region: asia-south1
    keyspace: main
    application.token: <token>





